const language = {
    loadevent: "Player event load ho gaya",
    loadcmd: "Command load ho gaya",
    ready: " successfully connect ho gaya.",
    loadslash: "Application [/] commands ko successfully reload kiya.",
    error1: "Jo Bot Token aapne project mein dala hai wo galat hai ya phir Bot ke INTENTS OFF hain!",
    error2: "Please apna bot token token.js ya .env file mein set karo!",
    loadclientevent: "Client event load ho gaya",
    embed1: "Aapke paas is server par <@&{djRole}>(DJ) role hona chahiye is command ko use karne ke liye. Jin users ke paas ye role nahi hai wo {cmdMAP} nahi use kar sakte",
    message1: "Aap kisi audio channel mein connected nahi ho. ❌",
    message2: "Aap mere saath wale audio channel mein nahi ho. ❌",
    message3: "Permission nahi mili",
    msg4: "Kuch galat ho gaya",
    msg5: "Abhi koi music nahi chal raha. ❌",
    msg6: "Music Save karo",
    msg7: "Playlist ka naam likho.",
    msg8: "Ye song live stream ho raha hai, duration dikhane ke liye data nahi hai. 🎧",
    msg9: "**✅ Success:** Time data update ho gaya.",
    msg10: "Aapke paas pehle se is naam ki playlist nahi hai. ❌",
    msg11: "Ye music pehle se is playlist mein hai. ❌",
    msg12: "Aapki music playlist mein add ho gaya.",
    error3: "Application [/] commands reload karte waqt error aaya: ",
    error4: "WARN: Aisa lagta hai aapne mongodb url nahi likha? Agar config.js file mein valid mongodb url nahi dala, toh bot kaam nahi karega.",
    msg13: `🎵 Abhi chal raha hai: **{track?.title}** -> Channel: **{queue?.connection.channel.name}** 🎧`,
    msg14: "Queue khaali hai. Aur music play kar sakte ho, byebye... ✅",
    msg15: "Maine disconnect kar diya kyunki mere channel mein koi nahi bacha. ❌",
    msg16: "Voice channel mein connect hone mein problem ho rahi hai. ❌ Kya kisi ne mujhe disconnect kar diya? Mujhe bahut bura lag raha hai. 😔",
    msg17: "Koi pichla track nahi hai! ❌",
    msg18: "Abhi chal raha hai **{queue.previousTracks[1].title}**. ✅",
    msg19: " Bot Statistics",
    msg20: "Refresh karo",
    msg21: "**Aapka Time Khatam Ho Gaya!**",
    msg22: "**✅ Data Update Ho Gaya.**",
    msg23: "Queue khaali hai. ❌",
    msg24: "Queue abhi abhi clear ho gayi. 🗑️",
    msg25: "DJ role ko successfully <@&{role}> pe set kar diya.",
    msg26: "Agar DJ role specify nahi kiya, toh aap command use nahi kar paoge!",
    msg27: "DJ role successfully delete ho gaya.",
    msg28: "DJ role pehle se set nahi hai.",
    msg29: `Please ek valid filter name dalo. ❌\n{filters}`,
    msg30: `Mujhe uss naam ka filter nahi mila. ❌\n{filters}`,
    msg31: `Apply kiya: **{filter}**, Filter Status: **{status}**\n **Yaad rahe, agar music lamba hai, toh filter apply hone mein zyada time lag sakta hai.**`,
    msg32: "Ab aapke discord server par music sunne ka time hai ek free aur advanced interface ke saath. Ek music bot jo kai platforms pe music play karne ko support karta hai. Apna music bot banao: https://github.com/umutxyp/MusicBot",
    msg33: "Bot Commands",
    msg34: "Aapke paas yahan pehle se ek active command hai. ❌",
    msg35: "Queue",
    msg36: "Abhi Chal Raha Hai",
    msg37: "Loop Band Karo",
    msg38: "Loop System",
    msg39: `> **Kya aap ek choice banana chahenge?**
   > **Queue:** Queue ko loop karega.
   > **Abhi Chal Raha Hai:** Current song ko loop karega.
   > **Loop Band Karo:** Loop ko band karega.`,
    msg40: "Queue Loop Mode",
    msg41: "Kuch galat ho gaya. ❌",
    msg42: "Abhi Chal Raha Hai Loop Mode",
    msg43: "Loop mode pehle se hi inactive hai. ❌",
    msg44: `Loop Mode **Band** 🔁`,
    msg45: "Time Khatam Ho Gaya",
    msg46: "Loop System - Khatam",
    msg47: 'Playlist Save Karo',
    msg48: "Music pause ho gaya! ✅",
    msg49: `Message Ping`,
    msg50: `Message Latency`,
    msg51: `API Latency`,
    msg52: `Koi playlist nahi hai. ❌`,
    msg53: `Aapko ye playlist play karne ki permission nahi hai. ❌`,
    msg54: `Aapke paas is naam ka music pehle se nahi hai. ❌`,
    msg55: `Main aapke voice channel mein join nahi ho sakta. ❌`,
    msg56: `Playlist load ho rahi hai... ✅`,
    msg57: `<@{interaction.member.id}>, **{music_filter.length}** tracks queue mein add ho gayi. ✅`,
    msg58: `Is naam ki koi playlist nahi hai. ❌`,
    msg59: `Us track ka naam likho jo aap search karna chahte ho. ❌`,
    msg60: `Koi result nahi mila! ❌`,
    msg61: "Music load ho raha hai... 🎧",
    msg62: "Named list playlist mein add ho gayi. ✅",
    msg63: `Queue khaali hai. ❌`,
    msg64: "Server Music List",
    msg65: "Abhi Chal Raha Hai",
    msg66: "Request kiya tha",
    msg67: "Page",
    msg68: `Command processor cancel ho gaya. ✅`,
    msg69: `Server Music List - Time Khatam Ho Gaya!`,
    msg70: `Aapka time khatam ho gaya command use karne ke liye, aap \`/queue\` likh ke command dobara use kar sakte ho.`,
    msg71: `Kuch galat ho gaya. ❌ Lagta hai aapne pehle music band nahi kiya.`,
    msg72: "Track resume ho gaya! ✅",
    msg73: `Please ek valid song name dalo. ❌`,
    msg74: `Koi search result nahi mila! ❌`,
    msg75: "Search Kiya Hua Music",
    msg76: "**1** se **{maxTracks.length}** tak ek gaana chuno ⬇️",
    msg77: `Music search cancel ho gaya. ✅`,
    msg78: `Loading... 🎧`,
    msg79: "Queue mein add ho gaya. ✅",
    msg80: `Song search ka time khatam ho gaya ❌`,
    msg81: "Cancel",
    msg82: `Aapne jo number dala hai wo queue mein songs ki quantity se zyada hai. ❌`,
    msg83: "Song skip ho gaya ✅",
    msg84: `Ye song live stream ho raha hai, duration dikhane ke liye data nahi hai. 🎧`,
    msg85: `Music band ho gaya. Phir milenge! ✅`,
    msg86: "Update",
    msg87: `Current volume: **{queue.volume}** 🔊`,
    msg88: `Jo volume aap change karna chahte ho wo pehle se hi set hai ❌`
}
module.exports = language; 
